// Toshokan — sample workspace data (typed port of the prototype's data.js).
// The visual-regression baseline and the contract the UI was built against.
// Served by the ipc layer while USE_FIXTURES is true.

import type { Project, Service, TreeNode, FilePreview } from "./types";

export const FIXTURE_PROJECTS: Project[] = [
  {
    id: "idolmancer",
    name: "Idolmancer",
    desc: "Music composition & theory workbench",
    tech: ["TypeScript", "React", "Tauri"],
    path: "~/Workspace/Idolmancer",
    lastOpened: "Today, 10:42 AM",
    sortKey: 0,
    branch: "main",
    repo: "Local only",
    serviceCount: 1,
    subprojects: [{ name: "Idolmancy - Megane", desc: "Chart editor extension", lastOpened: "Today, 10:42 AM" }],
    summary: {
      source: "README.md",
      updated: "Today, 9:15 AM",
      paragraphs: [
        "Idolmancer is a music composition and theory workbench: a single shell application hosting focused tools — chord generation, harmonic transitions, harmonics, BPM math, waveform and spectrum analysis, and EQ preview — each developed as its own package.",
        "Every tool exports a headless core of pure theory/DSP math, a React component, and a manifest the shell registers. Shared theory math, the offline audio engine, and UI components live in common packages so tools never duplicate logic.",
        "The app is offline-first and strictly client-side, wrapped in a thin Tauri shell for Windows 11 with a path to Android from the same codebase.",
        "Subproject “Idolmancy - Megane” is used for chart editing, UI inspection, and data visualization.",
      ],
      markdown: [
        "# Idolmancer",
        "",
        "A music composition and theory workbench. Idolmancer is a single shell",
        "application that presents many focused **tools** — each developed as its own",
        "project and imported into the shell to be displayed and organized on its own page.",
        "",
        "**Primary target:** Windows 11 desktop · **Planned:** Android mobile",
        "",
        "## Tools",
        "",
        "- **chordgen** — chord & progression generator (key / scale / genre / mood).",
        "- **transition engine** — harmonic voice-leading between keys and modes.",
        "- **harmonics**, **bpm-ms**, **waveform**, **spectrum**, **eq-preview**.",
        "",
        "## Architecture",
        "",
        "Every tool is a self-contained Vite + React + TypeScript package exporting a",
        "headless theory/DSP core, a React component, and a manifest the shell registers.",
        "",
        "| Layer | Responsibility |",
        "|---|---|",
        "| `apps/shell` | host app, registry, navigation |",
        "| `packages/theory-core` | pitch/scale/chord math |",
        "| `packages/audio-engine` | offline DSP (FFT, biquad EQ) |",
        "",
        "> Offline-first and strictly client-side; wrapped in a thin Tauri shell.",
      ].join("\n"),
    },
  },
  {
    id: "jagaimo",
    name: "Jagaimo",
    desc: "Read-only personal asset tracker",
    tech: ["Python", "React", "Supabase"],
    path: "~/Workspace/Jagaimo",
    lastOpened: "2d ago",
    sortKey: 4,
    branch: "main",
    repo: "Local only",
    serviceCount: 1,
    subprojects: [],
    summary: {
      source: "README.md",
      updated: "2d ago",
      paragraphs: [
        "Jagaimo snapshots everything held — stocks and ETFs, on-chain tokens, brokerage and exchange balances — values it all in USD every 15 minutes, and keeps price and candlestick history for held and watchlisted instruments.",
        "A Python core ingests from read-only sources (Alpaca, Base wallets, Vanguard CSV exports, Coinbase) and fires price-target and net-worth alerts to Telegram. It never trades: there are zero order-write calls, a grep-verifiable guarantee.",
        "A React viewer served over a private tailnet renders multi-timeframe charts, candlesticks, weighted baskets, point-in-time analytics, and the append-only trade ledger from a self-hosted Supabase database.",
        "The name is Japanese for potato — humble, dependable, keeps in the cellar.",
      ],
    },
  },
  {
    id: "sando",
    name: "Sando",
    desc: "Self-hosted household scheduler",
    tech: ["Python", "FastAPI"],
    path: "~/Workspace/Sando",
    lastOpened: "3d ago",
    sortKey: 5,
    branch: "main",
    repo: "Local only",
    serviceCount: 2,
    subprojects: [],
    summary: {
      source: "README.md",
      updated: "3d ago",
      paragraphs: [
        "Sando is a household scheduler for a single tailnet: a reminder daemon that watches reminders.json and sends Telegram messages at scheduled times, plus a FastAPI PWA calendar for viewing and editing the schedule from a phone.",
        "There is no database — the master schedule lives in monthly .xlsx workbooks, reminder state in reminders.json, an audit trail in changelog.csv. Everything is reasoned about in Hawaii time.",
        "Writes are dual-writes into the spreadsheet, the reminder file, and the changelog, coordinated through file locks so the daemon, the web app, and the host agent never race each other. 81 tests passing.",
      ],
    },
  },
  {
    id: "plastiglom",
    name: "Plastiglom",
    desc: "Daily self-reflection & analysis engine",
    tech: ["Python", "Claude API"],
    path: "~/Workspace/Plastiglom",
    lastOpened: "Today, 9:15 AM",
    sortKey: 1,
    branch: "main",
    repo: "Local only",
    serviceCount: 1,
    service: { label: "Web App", url: "http://localhost:8001" },
    subprojects: [],
    summary: {
      source: "README.md",
      updated: "Today, 9:15 AM",
      paragraphs: [
        "Plastiglom prompts daily self-reflection exercises, archives every response in an Obsidian vault, and uses an evolving memory to run weekly, monthly, and ad-hoc analysis across entries.",
        "A scheduler fires exercises morning and evening; an archiver finalizes entries; Sonnet taggers and Opus analyzers write digests and evidence-cited reports back into the vault. A Tailscale PWA serves prompts, stats, cost, and proposal review.",
        "Exercise changes are never auto-applied — the meta-engine proposes, the user approves, and every decision is logged. Analysis never overwrites entries or prior reports; corrections supersede through a logged channel.",
      ],
    },
  },
  {
    id: "frogbudget",
    name: "Frog Budget",
    desc: "Personal budget tracking PWA",
    tech: ["React", "TypeScript", "Supabase"],
    path: "~/Workspace/FrogBudget",
    lastOpened: "Yesterday, 4:31 PM",
    sortKey: 2,
    branch: "main",
    repo: "Local only",
    serviceCount: 1,
    service: { label: "Dev Server", url: "http://localhost:5173" },
    subprojects: [],
    summary: {
      source: "README.md",
      updated: "Yesterday, 4:31 PM",
      paragraphs: [
        "Frog Budget tracks purchases, allocates income percentages to category budgets, and shows spending against budget per category — with overspending alerts and projected end-of-month spending based on current pace.",
        "Built with React, TypeScript, and Vite over Supabase (Postgres, auth, realtime), so changes sync instantly across devices. Works in the browser on Windows and installs as a PWA on Android.",
        "Includes charts of spending trends and category breakdowns, CSV export of purchase data, and dark mode.",
      ],
    },
  },
  {
    id: "inventorois",
    name: "Inventorois",
    desc: "Household inventory manager",
    tech: ["React", "TypeScript", "Supabase"],
    path: "~/Workspace/Inventorois",
    lastOpened: "5d ago",
    sortKey: 6,
    branch: "main",
    repo: "Local only",
    serviceCount: 1,
    subprojects: [],
    summary: {
      source: "README.md",
      updated: "5d ago",
      paragraphs: [
        "Inventorois is a household inventory manager: items organized through nested categories and locations, with tags, favorites, and templates to speed up adding common things.",
        "Essential items can be flagged for low-stock alerts; every change lands in a history log with undo. Data syncs in real time through Supabase, is shared across the household, and exports to CSV.",
        "Runs in the browser on Windows and installs as a PWA on Android. Barcode scanning, image attachments, and shopping-list generation are on the roadmap.",
      ],
    },
  },
  {
    id: "kanimiso",
    name: "Kani-miso",
    desc: "Personal catalog & self-analysis engine",
    tech: ["Python", "SQLite", "Claude API"],
    path: "~/Workspace/Kani-miso",
    lastOpened: "6d ago",
    sortKey: 3,
    branch: "main",
    repo: "Local only",
    serviceCount: 1,
    subprojects: [],
    summary: {
      source: "README.md",
      updated: "6d ago",
      paragraphs: [
        "Kani-miso ingests personal captures — Telegram messages, an X/Twitter archive, articles, PDFs, images — into a faithful markdown catalog: an Obsidian vault organized through hub notes and tags.",
        "Captures flow through a SQLite queue into Claude processing and land as validated markdown. The repository is the engine only; the catalog lives in a separate private vault and is never committed.",
        "The analysis engine periodically generates candid, evidence-cited snapshots of the author's thinking, emotional patterns, philosophy, and life direction. Each snapshot is a dated checkpoint; the sequence is the record.",
        "Fidelity first: original capture text is preserved verbatim, and interpretation is asserted only from evidence.",
      ],
    },
  },
];

export const FIXTURE_SERVICES: Service[] = [
  {
    id: "svc-plastiglom",
    ram: 168,
    name: "Plastiglom",
    role: "Web App",
    projectId: "plastiglom",
    projectName: "Plastiglom",
    projectDesc: "Daily self-reflection & analysis engine",
    runtime: "uvicorn / FastAPI",
    command: "python -m plastiglom.apps.web_app",
    port: "localhost:8001",
    pid: "14288",
    uptime: "1h 22m",
    status: "running",
    kind: "server",
    detail: {
      launchCommand: "python -m plastiglom.apps.web_app --host 127.0.0.1 --port 8001",
      workingDir: "~/Workspace/Plastiglom",
      localUrl: "http://localhost:8001",
      started: "Today, 9:15 AM",
      user: "toshokan",
      environment: "LOCAL",
      log: [
        ["09:15:02", [["INFO ", "g"], ["Uvicorn running on http://127.0.0.1:8001", ""]]],
        ["09:15:02", [["INFO ", "g"], ["Application startup complete", ""]]],
        ["10:14:48", [["INFO ", "g"], ["GET /analysis 200 OK", ""]]],
        ["10:31:10", [["INFO ", "g"], ["GET /stats 200 OK", ""]]],
        ["10:36:55", [["INFO ", "g"], ["GET /proposals 200 OK", ""]]],
      ],
    },
  },
  {
    id: "svc-frogbudget",
    ram: 412,
    name: "Frog Budget",
    role: "Dev Server",
    projectId: "frogbudget",
    projectName: "Frog Budget",
    projectDesc: "Personal budget tracking PWA",
    runtime: "Vite",
    command: "npm run dev",
    port: "localhost:5173",
    pid: "15876",
    uptime: "48m",
    status: "running",
    kind: "server",
    detail: {
      launchCommand: "npm run dev",
      workingDir: "~/Workspace/FrogBudget",
      localUrl: "http://localhost:5173",
      started: "Today, 9:57 AM",
      user: "toshokan",
      environment: "LOCAL",
      log: [
        ["09:57:02", [["vite v5.2.3", "g"], [" ready in 384 ms", ""]]],
        ["09:57:02", [["➜  Local: ", ""], ["http://localhost:5173/", "b"]]],
        ["10:14:48", [["hmr update ", "g"], ["/src/components/BudgetCard.tsx", ""]]],
        ["10:31:10", [["✓  built in 176ms", ""]]],
      ],
    },
  },
  {
    id: "svc-megane",
    ram: 96,
    name: "Idolmancy - Megane",
    role: "Editor Preview",
    projectId: "idolmancer",
    projectName: "Idolmancer",
    projectDesc: "Music composition & theory workbench",
    runtime: "Next.js",
    command: "next dev -p 3001",
    port: "localhost:3001",
    pid: null,
    uptime: null,
    status: "starting",
    kind: "server",
    detail: {
      launchCommand: "pnpm --filter megane dev",
      workingDir: "~/Workspace/Idolmancer/idolmancy-Megane",
      localUrl: "http://localhost:3001",
      started: "Today, 10:44 AM",
      user: "toshokan",
      environment: "LOCAL",
      log: [
        ["10:44:51", [["▲ Next.js 14.2.1", ""]]],
        ["10:44:51", [["- Local: ", ""], ["http://localhost:3001", "b"]]],
        ["10:44:52", [["Starting...", "y"]]],
      ],
    },
  },
  {
    id: "svc-sando-web",
    ram: null,
    name: "Sando",
    role: "Web App",
    projectId: "sando",
    projectName: "Sando",
    projectDesc: "Self-hosted household scheduler",
    runtime: "uvicorn / FastAPI",
    command: "python -m uvicorn sando_web.app:app",
    port: "localhost:8765",
    pid: null,
    uptime: null,
    status: "stopped",
    kind: "server",
    detail: {
      launchCommand: "python -m uvicorn sando_web.app:app --host 127.0.0.1 --port 8765",
      workingDir: "~/Workspace/Sando",
      localUrl: "http://localhost:8765",
      started: "—",
      user: "toshokan",
      environment: "LOCAL",
      log: [],
    },
  },
  {
    id: "svc-sando-daemon",
    ram: 38,
    name: "Sando",
    role: "Reminder Daemon",
    projectId: "sando",
    projectName: "Sando",
    projectDesc: "Self-hosted household scheduler",
    runtime: "Python Daemon",
    command: "python reminder_daemon.py",
    port: null,
    pid: "1203",
    uptime: "14d 2h",
    status: "running",
    kind: "daemon",
    detail: {
      launchCommand: "python reminder_daemon.py",
      workingDir: "~/Workspace/Sando",
      localUrl: null,
      started: "May 29, 8:02 AM",
      user: "toshokan",
      environment: "LOCAL",
      log: [
        ["08:00:00", [["Weekly digest sent ", ""], ["(4 events this week)", "g"]]],
        ["09:00:11", [["poll: 0 reminders due", ""]]],
        ["10:00:09", [["poll: 1 due → sent ", ""], ["“Dentist — 1 hour before”", "b"]]],
        ["10:00:09", [["marked sent: true", "g"]]],
      ],
    },
  },
  {
    id: "svc-jagaimo",
    ram: 22,
    name: "Jagaimo",
    role: "Viewer",
    projectId: "jagaimo",
    projectName: "Jagaimo",
    projectDesc: "Read-only personal asset tracker",
    runtime: "Caddy (static)",
    command: "caddy run --config Caddyfile",
    port: "tailnet :443",
    pid: "882",
    uptime: "6d 11h",
    status: "running",
    kind: "server",
    detail: {
      launchCommand: "caddy run --config viewer/deploy/Caddyfile",
      workingDir: "~/Workspace/Jagaimo/viewer",
      localUrl: "https://jagaimo.tailnet",
      started: "Jun 6, 11:02 PM",
      user: "toshokan",
      environment: "LOCAL",
      log: [
        ["23:02:14", [["INFO ", "g"], ["serving viewer/dist on tailnet interface", ""]]],
        ["08:12:44", [["INFO ", "g"], ["GET /portfolio 200", ""]]],
        ["10:40:31", [["INFO ", "g"], ["GET /instruments 200", ""]]],
      ],
    },
  },
  {
    id: "svc-inventorois",
    ram: null,
    name: "Inventorois",
    role: "Dev Server",
    projectId: "inventorois",
    projectName: "Inventorois",
    projectDesc: "Household inventory manager",
    runtime: "Vite",
    command: "npm run dev",
    port: "localhost:3000",
    pid: "19844",
    uptime: "2m",
    status: "failed",
    kind: "server",
    error: {
      code: "Exited with code 1",
      message: "Error: Port 3000 is already in use",
      time: "Today, 10:43 AM",
    },
    detail: {
      launchCommand: "npm run dev",
      workingDir: "~/Workspace/Inventorois",
      localUrl: "http://localhost:3000",
      started: "Today, 10:41 AM",
      user: "toshokan",
      environment: "LOCAL",
      log: [
        ["10:41:33", [["vite v5.1.6", "g"], [" starting...", ""]]],
        ["10:43:02", [["Error: Port 3000 is already in use", "r"]]],
        ["10:43:02", [["npm ERR! ", "r"], ["Lifecycle script `dev` failed with error", ""]]],
      ],
    },
  },
  {
    id: "svc-kanimiso",
    ram: null,
    name: "Kani-miso",
    role: "Capture Processor",
    projectId: "kanimiso",
    projectName: "Kani-miso",
    projectDesc: "Personal catalog & self-analysis engine",
    runtime: "Python",
    command: "python scripts/processor.py",
    port: null,
    pid: null,
    uptime: null,
    status: "stopped",
    kind: "daemon",
    detail: {
      launchCommand: "python scripts/processor.py",
      workingDir: "~/Workspace/Kani-miso",
      localUrl: null,
      started: "—",
      user: "toshokan",
      environment: "LOCAL",
      log: [],
    },
  },
];

export const FIXTURE_TREE: TreeNode[] = [
  { name: ".github", type: "dir", modified: "Mon, 11:20 AM", children: [
    { name: "workflows", type: "dir", modified: "Mon, 11:20 AM", children: [
      { name: "ci.yml", type: "file", size: "1.4 KB", modified: "Mon, 11:20 AM" },
    ] },
  ] },
  { name: "apps", type: "dir", modified: "Today, 8:55 AM", children: [
    { name: "shell", type: "dir", modified: "Today, 8:55 AM", children: [] },
  ] },
  { name: "packages", type: "dir", modified: "Today, 8:20 AM", children: [
    { name: "audio-engine", type: "dir", modified: "Yesterday, 5:12 PM", children: [] },
    { name: "data-model", type: "dir", modified: "Mon, 1:44 PM", children: [] },
    { name: "storage", type: "dir", modified: "Mon, 1:44 PM", children: [] },
    { name: "theory-core", type: "dir", modified: "Today, 8:20 AM", children: [] },
    { name: "tokens", type: "dir", modified: "Mon, 11:20 AM", children: [] },
    { name: "ui", type: "dir", modified: "Yesterday, 2:10 PM", children: [] },
  ] },
  { name: "tools", type: "dir", modified: "Today, 8:37 AM", children: [
    { name: "bpm-ms", type: "dir", modified: "Yesterday, 6:02 PM", children: [] },
    { name: "chordgen", type: "dir", modified: "Today, 8:37 AM", children: [] },
    { name: "eq-preview", type: "dir", modified: "Yesterday, 4:21 PM", children: [] },
    { name: "harmonics", type: "dir", modified: "Mon, 3:05 PM", children: [] },
    { name: "spectrum", type: "dir", modified: "Yesterday, 2:10 PM", children: [] },
    { name: "transition-engine", type: "dir", modified: "Today, 8:29 AM", children: [] },
    { name: "waveform", type: "dir", modified: "Yesterday, 2:10 PM", children: [] },
  ] },
  { name: "idolmancy-Megane", type: "dir", modified: "Today, 10:42 AM", running: true, children: [
    { name: "src", type: "dir", modified: "Today, 10:42 AM", children: [] },
    { name: "package.json", type: "file", size: "1.1 KB", modified: "Today, 10:02 AM" },
  ] },
  { name: "notes", type: "dir", modified: "Today, 9:15 AM", children: [
    { name: "Idolmancer.md", type: "file", size: "2.2 KB", modified: "Today, 9:15 AM" },
  ] },
  { name: "src-tauri", type: "dir", modified: "Mon, 4:48 PM", children: [
    { name: "tauri.conf.json", type: "file", size: "2.0 KB", modified: "Mon, 4:48 PM" },
    { name: "Cargo.toml", type: "file", size: "780 B", modified: "Mon, 4:48 PM" },
  ] },
  { name: "README.md", type: "file", size: "5.6 KB", modified: "Today, 9:10 AM" },
  { name: "PLAN.md", type: "file", size: "18 KB", modified: "Mon, 11:20 AM" },
  { name: "package.json", type: "file", size: "920 B", modified: "Mon, 11:20 AM" },
  { name: "pnpm-workspace.yaml", type: "file", size: "118 B", modified: "Mon, 11:20 AM" },
  { name: ".gitignore", type: "file", size: "312 B", modified: "Mon, 11:20 AM" },
  { name: "toshokan.yml", type: "file", size: "842 B", modified: "Today, 9:01 AM" },
];

export const FIXTURE_FILE_PREVIEWS: Record<string, FilePreview> = {
  "README.md": {
    kind: "Markdown",
    size: "5.6 KB",
    modified: "Today, 9:10 AM",
    lines: [
      "# Idolmancer",
      "",
      "A music composition and theory workbench. Idolmancer is a single shell",
      "application that presents many focused tools — each developed as its own",
      "project and imported into the shell to be displayed and organized.",
      "",
      "Primary target: Windows 11 desktop · Planned: Android mobile",
    ],
  },
  "toshokan.yml": {
    kind: "YAML",
    size: "842 B",
    modified: "Today, 9:01 AM",
    lines: [
      "name: Idolmancer",
      "launch: pnpm dev",
      "notes: notes/Idolmancer.md",
      "services:",
      "  - name: Editor Preview",
      "    command: pnpm --filter megane dev",
      "    port: 3001",
    ],
  },
  "package.json": {
    kind: "JSON",
    size: "920 B",
    modified: "Mon, 11:20 AM",
    lines: [
      "{",
      '  "name": "idolmancer",',
      '  "private": true,',
      '  "scripts": {',
      '    "dev": "pnpm --filter shell dev",',
      '    "build": "pnpm -r build",',
      '    "test": "vitest"',
      "  }",
      "}",
    ],
  },
};
